services:
    mysql:
      image: mysql:8.0
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      container_name: database
      volumes:
        - ./mysql/mysql/:/docker-enterpoint-initdb.database
      environment:
        MYSQL_USER: ${DB_USER}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_RANDOM_ROOT_PASSWORD: 0
        MYSQL_ROOT_HOST: ${DB_ROOT_HOST}
      ports:
        - "3306:3306"
      

