services:
    backend:
      build: .
      restart: always
      image: ghcr.io/int221/back-end:master
      container_name: backend
      ports:
        - "9000:9000"
      networks:
        - default
  #define network
networks:
    default:
      external:
        name: projectnetwork