version: '3'
services:
  database:
    build: .
    container_name: database
    volumes:
      - ./Database/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
networks:
  default:
    external:
      name: projectnetwork
      

